from team import Team
class League:
        class Team:
            def __init__(self):
                self.team = []
                self.create_team()

            def create_team(self):
                t28 = Team("Toronto Maple Leafs", 70, 50, 40)
                t8 = Team("Chicago Blackhawks", 20, 20, 40)
                t25 = Team("San Jose Sharks", 20, 20, 20)
                t21 = Team("Ottawa Senators", 40, 50, 20)
                t22 = Team("Philadelphia Flyers", 50, 60, 20)
                t1 = Team("Anaheim Ducks", 50, 60, 20)
                t7 = Team("Calgary Flames", 40, 50, 30)
                t18 = Team("New Jersey Devils", 70, 40, 30)
                t2 = Team("Arizona Coyotes", 40, 40, 30)
                t31 = Team("Washington Capitals", 30, 30, 40)
                t27 = Team("Tampa Bay Lightning", 50, 50, 50)
                t29 = Team("Vancouver Canucks", 50, 60, 50)
                t16 = Team("Montreal Canadiens", 30, 30, 40)
                t6 = Team("Columbus Blue Jackets", 40, 20, 40)
                t10 = Team("Dallas Stars", 60, 60, 50)
                t30 = Team("Vegas Golden Knights", 60, 50, 50)
                t23 = Team("Pittsburgh Penguins", 70, 40, 50)
                t9 = Team("Colorado Avalanche", 70, 40, 50)
                t19 = Team("New York Islanders", 60, 40, 60)
                t15 = Team("Minnesota Wild", 40, 70, 50)
                t11 = Team("Detroit Red Wings", 30, 40, 50)
                t4 = Team("Buffalo Sabres", 50, 30, 50)
                t20 = Team("New York Rangers", 40, 50, 60)
                t17 = Team("Nashville Predators", 60, 60, 60)
                t12 = Team("Edmonton Oilers", 80, 60, 60)
                t14 = Team("Los Angeles Kings", 60, 70, 60)
                t26 = Team("St. Louis Blues", 30, 30, 60)
                t5 = Team("Carolina Hurricanes", 70, 80, 70)
                t24 = Team("Seattle Kraken", 40, 70, 70)
                t13 = Team("Florida Panthers", 60, 80, 70)
                t3 = Team("Boston Bruins", 50, 50, 70)
                t32 = Team("Winnipeg Jets", 60, 60, 80)

                self.Team.append(t1)
                self.Team.append(t2)
                self.Team.append(t3)
                self.Team.append(t4)
                self.Team.append(t5)
                self.Team.append(t6)
                self.Team.append(t7)
                self.Team.append(t8)
                self.Team.append(t9)
                self.Team.append(t10)
                self.Team.append(t11)
                self.Team.append(t12)
                self.Team.append(t13)
                self.Team.append(t14)
                self.Team.append(t15)
                self.Team.append(t16)
                self.Team.append(t17)
                self.Team.append(t18)
                self.Team.append(t19)
                self.Team.append(t20)
                self.Team.append(t21)
                self.Team.append(t22)
                self.Team.append(t23)
                self.Team.append(t24)
                self.Team.append(t25)
                self.Team.append(t26)
                self.Team.append(t27)
                self.Team.append(t28)
                self.Team.append(t29)
                self.Team.append(t30)
                self.Team.append(t31)
                self.Team.append(t32)
